language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - javaducky@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: PR5EHF5D18ABpU5lz0VJI2CnJ3Yr2pLm22vC60z9XRvlKikIj7tzCQYtE7w1mUnFt4+mJ8t3t100WfqfC9pp0aNpbBziPqTmQI/ErcrIoEiCs+1yKS1wXzSTRQBkBuRz1uoycqS5E+IjJO8Q/9DmBQTVA8qenJJx+ZeN0twQOkZ82bhJxjROkB+HEzeGbZ1cbcq1MSnedvjkP7y+eRdXKniwp+uQ0Zo2hnZ4tbTSWCN6PgOf3F1WZimQAe23M1gIhssdva0FwbTXbI7xSmmaM2H1kMnJbYlwZXLZDMjOOSH/NwB7vnWnmF1pAxrBUFI/yaZ3Xvrm0jaRmCd1yrUB/deD9Tm95zlbVVRJCws8TGiF5Sb9q7VhqjK1fxGGUAE5Jv303E7/S8WhB7Y9dCW+wIxzo+6qfdh4gdknIghcY6pWMJEZiet2UDAq9nLRxgcF6X0qg8NHu9mu6ekJpqLwgUJK9GeawXqH7Eiq2PM+JD6BCXwwV5CsZy/tPfdSc+qGuBgkGpu241p1Ql+dn/f9hCvTHPRpjr/51r6H/ZrVJxiamZ3lq6lkOLyT5F/b07KxUK+KzVltm+I2dwA1RG9xFImogTpIHNcqhXXY3RUusFV+H+7kumna+yN0UrXVLwECsAkVgmk0rE8s4RlddErqu6GIFgU8fuQucz8hfrHaeqk=
  - secure: QeW942y7TbR9N2GAvuY96AYQOIff/BEMi5ZanhB7ZjqGe9L95ZhGZHQ3s2GAOPvBafewtoxLBn8UhDoJS1NH+Cr5thtlX4aSH2IaMBzEdeOLzMI2vQUdtBTxGYQwcOn6yeFb40rl9/yKQ4oRbJ8oubM8x6Fxn4XPq1Bor3aZEMKNJkckYtt70bBb4penum4C0yiJVJgUc06EFOj3lvvk1UL7y1A96ML2S0wwv0778Rp5eRUXl119SaincBbgWAL0UflbfG8obGQb7MVWz7E2MOp4ptu6caOKFXqo1+joBT1zK//jEUIxKEe7RQiGTMVMMVUX4PzzxyfrtCpmMr+nLvksTXZpDrszftWf0flVNiDmzKxTAZlqvOZ+lzAHrteeb9UiI6ef4P1bjCbz391m5VZUH6vqlWy3jmGRLQjLmcZDsFzqb8vPYFgp4CcpY22ZVFD+C9C8wyCtHTwAr/sDEcCMeKmwdw9lc7tNZhI+7p0VZOXueBHVY4MINc7M9BrREGiHRemYNwUeg9aIZVQCZow49HF7sYh/DogWLIeQ416K3Bjm8wYgf0KEVrzVOwsziO/PJwGPIV+znECUD5g0I3OsqDwJlWYP2V/RImBi9GjjjvihQ/uZt3sq0gQvb502l4FsaK5KFswUqy1RbRZ/AYV0HdesNPP4J6xTxHEwaJ0=
  matrix:
  - TEST_DIR=licensing-service;TMX_DOCKER_IMAGE=javaducky/tmx-licensing-service:chapter4
  - TEST_DIR=organization-service;TMX_DOCKER_IMAGE=javaducky/tmx-organization-service:chapter4
  - TEST_DIR=confsvr;TMX_DOCKER_IMAGE=javaducky/tmx-confsvr:chapter4
  - TEST_DIR=eurekasvr;TMX_DOCKER_IMAGE=javaducky/tmx-eurekasvr:chapter4
script:
- cd $TEST_DIR
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $TMX_DOCKER_IMAGE
